import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import { AgentManager } from "./manager.ts";
import { SessionManager } from "@earendil-works/pi-coding-agent";
import { createPrimaryChannel, type PrimaryChannel } from "./primary-channel.ts";
import { EFFORT_PURPOSE_ENTRY, retainedPurpose } from "./effort-purpose.ts";

it("samples activity writes and keeps observed purpose separate from declared intent", async (t) => {
	const root = mkdtempSync(join(tmpdir(), "effort-manager-"));
	let channel: PrimaryChannel | undefined;
	let touches = 0;
	const manager = new AgentManager({ root, agentDir: join(root, "agent"), packageDir: root, createPrimary: async (options) => {
		const created = await createPrimaryChannel(options);
		channel = created;
		return { ...created, touch: (at) => { touches++; created.touch(at); } };
	} });
	const signal = new AbortController();
	t.after(async () => { signal.abort(); manager.close(); await channel?.close(); rmSync(root, { recursive: true, force: true }); });
	const id = randomUUID();
	await manager.registerPrimary(id, { signal: signal.signal, cwd: root, send: () => {}, observedInput: "Review the parser" });
	assert.ok(channel);
	assert.equal(channel.info().observedPurpose?.source, "interactive-input");
	const lastActivityAt = channel.info().lastActivityAt;
	assert.ok(lastActivityAt);
	const at = Date.parse(lastActivityAt);
	manager.touchPrimary(id, at + 1000);
	manager.touchPrimary(id, at + 59_999);
	assert.equal(touches, 0);
	manager.touchPrimary(id, at + 60_000);
	manager.touchPrimary(id, at + 60_001);
	assert.equal(touches, 1);
	const intent = { purpose: "Declared review", integration: "Run one full gate", authority: "Operator permits this review", scope: { paths: ["src"], branches: ["work"], fullGate: true } };
	const result = await manager.publishIntent(id, intent);
	assert.equal(result.published.intentClaim?.purpose, intent.purpose);
	assert.equal(result.awareness.self.intentClaim?.scope.fullGate, true);
	manager.updatePrimary(id, { name: "Parser effort" });
	assert.deepEqual(channel.info().observedPurpose, { source: "session-name", text: "Parser effort" });
	assert.equal(channel.info().intentClaim?.purpose, intent.purpose);
	manager.updatePrimary(id, { name: undefined });
	assert.equal(channel.info().observedPurpose?.text, "Review the parser");
	await manager.publishIntent(id, undefined);
	assert.equal(channel.info().intentClaim, undefined);
	assert.equal(channel.info().observedPurpose?.text, "Review the parser");
	assert.equal(manager.recordPrimaryInput(id, "Second operator prompt", "interactive"), false);
});

it("does not replace unvisited first-input provenance after resume", async (t) => {
	const root = mkdtempSync(join(tmpdir(), "effort-resume-"));
	let channel: PrimaryChannel | undefined;
	const manager = new AgentManager({ root, agentDir: root, packageDir: root, createPrimary: async (options) => {
		channel = await createPrimaryChannel(options);
		return channel;
	} });
	t.after(async () => { manager.close(); await channel?.close(); rmSync(root, { recursive: true, force: true }); });
	const session = SessionManager.inMemory(root);
	session.appendCustomEntry(EFFORT_PURPOSE_ENTRY, { source: "interactive", text: "Original task" });
	for (let i = 0; i < 256; i++) session.appendCustomEntry("other");
	const purpose = retainedPurpose(session);
	const id = randomUUID();
	await manager.registerPrimary(id, { signal: new AbortController().signal, cwd: root, send: () => {}, observedInput: purpose.text, observedInputComplete: purpose.complete, observedInputCanCapture: purpose.canCapture });
	assert.equal(manager.recordPrimaryInput(id, "A later task", "interactive"), false);
	const view = await manager.awareness(id);
	assert.equal(view.self.observedPurpose, undefined);
	assert.equal(view.self.omitted, true);
	manager.updatePrimary(id, { name: "Named purpose" });
	const named = await manager.awareness(id);
	assert.equal(named.self.observedPurpose?.text, "Named purpose");
	assert.equal(named.self.omitted, undefined);
});

it("carries the current primary name and published purpose on direct session messages", async (t) => {
	const root = mkdtempSync(join(tmpdir(), "primary-sender-"));
	const manager = new AgentManager({ root, agentDir: root, packageDir: root });
	const senderId = randomUUID(), recipientId = randomUUID();
	const senderSignal = new AbortController();
	const received: Array<{ details?: unknown; replyTo?: string; text: string }> = [];
	const recipient = await createPrimaryChannel({ id: recipientId, cwd: root, sessionsRoot: root, deliver: (message) => { received.push(message); }, promptTrust: async () => undefined });
	t.after(async () => { senderSignal.abort(); manager.close(); await recipient.close(); rmSync(root, { recursive: true, force: true }); });
	await manager.registerPrimary(senderId, { signal: senderSignal.signal, cwd: root, send: () => {}, name: "Registered source", observedInput: "Review the parser" });
	await manager.control("submit", { sessionId: recipientId, message: "Direct message", requestId: "named", replyTo: senderId, origin: "operator" }, { id: senderId, cwd: root, name: "Current source", model: { provider: "provider", modelId: "model" }, thinkingLevel: "high" });
	const named = received[0]?.details as Record<string, unknown>;
	assert.equal(named.name, "Current source");
	assert.equal(named.kind, "message");
	assert.equal(named.senderKind, "session");
	assert.equal(named.senderIdentity, senderId);
	assert.equal(named.provider, "provider");
	assert.equal(named.modelId, "model");
	assert.equal(named.thinkingLevel, "high");
	assert.equal(named.wake, false);
	assert.equal(received[0]?.replyTo, senderId);
	assert.equal(received[0]?.text, "Direct message");
	manager.updatePrimary(senderId, { name: undefined });
	await manager.control("submit", { sessionId: recipientId, message: "Purpose message", requestId: "purpose", origin: "operator" }, { id: senderId, cwd: root });
	const purpose = received[1]?.details as Record<string, unknown>;
	assert.equal(purpose.name, undefined);
	assert.equal(purpose.observedPurpose, "Review the parser");
	assert.equal(purpose.provider, undefined);
	assert.equal(purpose.modelId, undefined);
	assert.equal(purpose.thinkingLevel, undefined);
	const receipt = await manager.control("report", { sessionId: recipientId, message: "Explicit report", requestId: "report", origin: "model" }, { id: senderId, cwd: root }) as { boundary: string };
	assert.doesNotMatch(receipt.boundary, /waits.*run to end/u, "a primary receipt does not claim Durable follow-up delivery");
	const report = received[2]?.details as Record<string, unknown>;
	assert.equal(report.kind, "report");
	assert.equal(report.wake, true);
});
